databases:
  - name: spend-tracker
    databaseName: spend_tracker_production
    user: st_user

services:
  - type: web
    name: spend_tracker
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spend_tracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
